#include "lan_chat/core/status.h"

const char *lan_chat_status_name(lan_chat_status_t status)
{
    switch (status) {
    case LAN_CHAT_STATUS_OK:
        return "LAN_CHAT_STATUS_OK";
    case LAN_CHAT_STATUS_INVALID_ARGUMENT:
        return "LAN_CHAT_STATUS_INVALID_ARGUMENT";
    case LAN_CHAT_STATUS_NOT_IMPLEMENTED:
        return "LAN_CHAT_STATUS_NOT_IMPLEMENTED";
    case LAN_CHAT_STATUS_OUT_OF_MEMORY:
        return "LAN_CHAT_STATUS_OUT_OF_MEMORY";
    case LAN_CHAT_STATUS_STORAGE_ERROR:
        return "LAN_CHAT_STATUS_STORAGE_ERROR";
    case LAN_CHAT_STATUS_NETWORK_ERROR:
        return "LAN_CHAT_STATUS_NETWORK_ERROR";
    case LAN_CHAT_STATUS_INTERNAL_ERROR:
        return "LAN_CHAT_STATUS_INTERNAL_ERROR";
    case LAN_CHAT_STATUS_NEED_MORE_DATA:
        return "LAN_CHAT_STATUS_NEED_MORE_DATA";
    case LAN_CHAT_STATUS_BAD_MAGIC:
        return "LAN_CHAT_STATUS_BAD_MAGIC";
    case LAN_CHAT_STATUS_UNSUPPORTED_VERSION:
        return "LAN_CHAT_STATUS_UNSUPPORTED_VERSION";
    case LAN_CHAT_STATUS_BAD_HEADER:
        return "LAN_CHAT_STATUS_BAD_HEADER";
    case LAN_CHAT_STATUS_BODY_TOO_LARGE:
        return "LAN_CHAT_STATUS_BODY_TOO_LARGE";
    case LAN_CHAT_STATUS_UNSUPPORTED_FIELD:
        return "LAN_CHAT_STATUS_UNSUPPORTED_FIELD";
    case LAN_CHAT_STATUS_DUPLICATE_FIELD:
        return "LAN_CHAT_STATUS_DUPLICATE_FIELD";
    case LAN_CHAT_STATUS_BUFFER_TOO_SMALL:
        return "LAN_CHAT_STATUS_BUFFER_TOO_SMALL";
    case LAN_CHAT_STATUS_ALREADY_EXISTS:
        return "LAN_CHAT_STATUS_ALREADY_EXISTS";
    case LAN_CHAT_STATUS_NOT_FOUND:
        return "LAN_CHAT_STATUS_NOT_FOUND";
    case LAN_CHAT_STATUS_INVALID_STATE:
        return "LAN_CHAT_STATUS_INVALID_STATE";
    default:
        return "LAN_CHAT_STATUS_UNKNOWN";
    }
}
